class EventCodes:
    PACKET_IN_NETWORK = 0
    PACKET_ARRIVED_SWITCH = 1
    PACKET_OUTSIDE_SWITCH_QUEUE = 2
    PACKET_ARRIVED_HOST = 3
    PACKET_PROCESS_FINISHED = 4
    PACKET_LEFT_DATACENTER = 5
    PACKET_TRANSMITTED = 6

    PACKET_DROPPED = -1
